
DROP TRIGGER trigger_membre_id;
DROP PROCEDURE TULIP_UPDATE;
DROP SEQUENCE membre_id_seq;

CREATE SEQUENCE membre_id_seq
                INCREMENT BY 1
                START WITH 10
                MAXVALUE 9999
                NOCACHE
                NOCYCLE;

CREATE OR REPLACE TRIGGER trigger_membre_id
      BEFORE INSERT ON membre
      FOR EACH ROW
    BEGIN
        IF :NEW.id_membre IS NULL THEN
          SELECT  membre_id_seq.NEXTVAL INTO :NEW.id_membre FROM dual;
        END IF;
    END;
/


CREATE OR REPLACE PROCEDURE TULIP_UPDATE 
(
  IDMEMBRE IN MEMBRE.ID_MEMBRE%TYPE 
) AS 
stat STATUT.STATUT_NAME%TYPE;
BEGIN
  SELECT S.STATUT_NAME INTO stat 
  FROM STATUT S JOIN MEMBRE MB ON (S.ID = MB.ID_STATUT) WHERE MB.ID_MEMBRE = IDMEMBRE ;
  IF(stat <> 'bronze') THEN
    UPDATE membre 
    SET ID_STATUT = (SELECT ID FROM STATUT WHERE STATUT_NAME = 'bronze')
    WHERE ID_MEMBRE = IDMEMBRE;
  END IF;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
  RAISE_APPLICATION_ERROR (-20222, 'WRONG MEMBER ID');
COMMIT;
END TULIP_UPDATE;
/
